package com.multimodalAgent.agent.runtime;

public enum AgentStopReason {
    COMPLETED,
    TOOL_ERROR,
    POLICY_BLOCKED,
    WAITING_APPROVAL,
    MODEL_ERROR,
    MODEL_TIMEOUT,
    MODEL_OUTPUT_LIMIT,
    BUDGET_EXHAUSTED,
    BUDGET_UNVERIFIABLE,
    MAX_ITERATIONS,
    CANCELLED,
    INTERNAL_ERROR
}
