package com.multimodalAgent.agent.recovery;

public enum RecoveryReason {
    ELIGIBLE,
    RUN_NOT_FOUND,
    RUN_TERMINAL,
    RUN_NOT_STARTED,
    MISSING_CHECKPOINT,
    AWAITING_APPROVAL,
    MISSING_APPROVAL_CHECKPOINT,
    AMBIGUOUS_TOOL_EXECUTION,
    IN_FLIGHT_MODEL_ATTEMPT,
    CHECKPOINT_BEHIND_CONFIRMED_MODEL_FACT,
    CHECKPOINT_BEHIND_CONFIRMED_TOOL_FACT,
    UNRESOLVED_MODEL_CONTROL_STATE,
    INCONSISTENT_MODEL_HISTORY,
    INCONSISTENT_TOOL_HISTORY,
    INCONSISTENT_CHECKPOINT_STATE
}
